"""create citations, street sweeping segments and street sweeping point

Revision ID: 03330763100f
Revises: d83a116d42e1
Create Date: 2023-05-25 18:54:20.840164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03330763100f'
down_revision = 'd83a116d42e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('steet_sweeping_segments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('cnn', sa.String(length=255), nullable=True),
    # sa.Column('corridor', sa.DateTime(), nullable=True),
    # sa.Column('limits', sa.DateTime(), nullable=True),
    # sa.Column('cnn_right_left', sa.String(length=255), nullable=True),
    # sa.Column('block_side', sa.String(length=255), nullable=True),
    # sa.Column('full_name', sa.String(length=255), nullable=True),
    # sa.Column('weekday', sa.String(length=255), nullable=True),
    # sa.Column('from_hour', sa.Integer(), nullable=True),
    # sa.Column('to_hour', sa.Integer(), nullable=True),
    # sa.Column('week1', sa.Integer(), nullable=True),
    # sa.Column('week2', sa.Integer(), nullable=True),
    # sa.Column('week3', sa.Integer(), nullable=True),
    # sa.Column('week4', sa.Integer(), nullable=True),
    # sa.Column('week5', sa.Integer(), nullable=True),
    # sa.Column('holidays', sa.Integer(), nullable=True),
    # sa.Column('block_sweep_id', sa.Integer(), nullable=True),
    # sa.Column('line', sa.String(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('street_sweeping_points',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('latitude', sa.Float(), nullable=True),
    # sa.Column('longitude', sa.Float(), nullable=True),
    # sa.Column('street_sweeping_segment_id', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street_sweeping_points')
    op.drop_table('steet_sweeping_segments')
    # ### end Alembic commands ###
