"""change datatypes for street sweeping segment

Revision ID: 036aee601f4b
Revises: 03330763100f
Create Date: 2023-05-25 19:21:04.567185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036aee601f4b'
down_revision = '03330763100f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
