"""add  ticket_data table

Revision ID: 85ad60d5a13d
Revises: f18e26ed5250
Create Date: 2023-07-12 15:34:18.538414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ad60d5a13d'
down_revision = 'f18e26ed5250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('total_tocket_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_tocket_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total_tickets', sa.INTEGER(), nullable=True),
    sa.Column('violation_desc', sa.VARCHAR(length=255), nullable=True),
    sa.Column('relative_frequency', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
