"""add bad_address

Revision ID: 8a935984dccf
Revises: b1638cd17979
Create Date: 2023-07-06 16:01:32.820849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a935984dccf'
down_revision = 'b1638cd17979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citations', sa.Column('bad_address', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citations', 'bad_address')
    # ### end Alembic commands ###
