"""add geocode_failed column

Revision ID: afb2cc76dacc
Revises: cc2703e35de7
Create Date: 2023-05-26 09:56:39.317190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb2cc76dacc'
down_revision = 'cc2703e35de7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citations', sa.Column('geocode_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citations', 'geocode_failed')
    # ### end Alembic commands ###
