"""add street_sweeping_segment_id to citations

Revision ID: cc2703e35de7
Revises: 036aee601f4b
Create Date: 2023-05-25 20:09:51.029088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2703e35de7'
down_revision = '036aee601f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citations', sa.Column('street_sweeping_segment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citations', 'street_sweeping_segment_id')
    # ### end Alembic commands ###
